const data = [
    {
        name: '아이스커피',
        price: 4100,
        imgUrl: './image/브루드 커피/아이스커피.jpg',
        description: '케냐, 하우스 블렌드 등 약간의 산미가 있는 커피를 드립 방식으로 추출한 후 얼음과 함께 제공하는 커피 입니다.아이스 커피로 적합한 프리미엄 원두를 이용하여 깔끔하고 상큼한 맛을 느끼실 수 있습니다.',
        type: 'brewed',
    },
    {
        name: '오늘의 커피',
        price: 3800,
        imgUrl: './image/브루드 커피/오늘의 커피.jpg',
        description: '시즌에 어울리는 원두 종류를 선정하여 신선하게 브루드(Brewed)되어 제공되는 드립커피로, 원두 커피의 풍부한 맛과 향을 따뜻하게 즐기실 수 있습니다.',
        type: 'brewed',
    },
    {
        name: '아이스 플랫 화이트',
        price: 6500,
        imgUrl: './image/에스프레소/아이스 플랫 화이트.jpg',
        description: '부드러운 리스트레토 샷과 완벽한 양의 우유를 더해, 카페 라떼보다 커피의 맛을 진하게 즐길 수 있는 에스프레소 음료입니다',
        type: 'espresso',
    },
    {
        name: '에스프레소 콘 파나',
        price: 4100,
        imgUrl: './image/에스프레소/에스프레소 콘 파나.jpg',
        description: '신선한 에스프레소 샷에 풍부한 휘핑크림을 얹은 커피 음료로서, 뜨거운 커피의 맛과 차갑고 달콤한 생크림의 맛을 같이 즐길 수 있는 커피 음료',
        type: 'espresso',
    },
    {
        name: '카페라떼',
        price: 5100,
        imgUrl: './image/에스프레소/카페라떼.jpg',
        description: '풍부하고 진한 에스프레소가 신선한 스팀 밀크를 만나 부드러워진 커피 위에 우유 거품을 살짝 얹은 대표적인 커피 라떼',
        type: 'espresso',
    },
    {
        name: '돌체 콜드 브루',
        price: 5100,
        imgUrl: './image/콜드브루/돌체 콜드 브루.jpg',
        description: '무더운 여름철, 동남아 휴가지에서 즐기는 커피를 떠오르게 하는 스타벅스 음료의 베스트 x 베스트 조합인 돌체 콜드 브루를 만나보세요!',
        type: 'coldBrew',
    },
    {
        name: '민트 콜드 브루',
        price: 5100,
        imgUrl: './image/콜드브루/민트 콜드 브루.jpg',
        description: '상쾌한 민트향 시럽과 잘게 갈린 얼음이 어우러져 시원함이 강렬하게 느껴지는 리저브만의 콜드 브루 음료',
        type: 'coldBrew',
    },
    {
        name: '씨솔트 카라멜 콜드 브루',
        price: 5100,
        imgUrl: './image/콜드브루/씨솔트 카라멜 콜드 브루.jpg',
        description: '구름 처럼 부드러운 씨솔트 폼과 번트 카라멜의 중독성 강한 단짠단짠 조합의 콜드 브루 한번 맛보면 자꾸 생각나는 매력적인 음료',
        type: 'coldBrew',
    },
    {
        name: '콜드 브루',
        price: 5100,
        imgUrl: './image/콜드브루/콜드 브루.jpg',
        description: '스타벅스 바리스타의 정성으로 탄생한 콜드 브루! 콜드 브루 전용 원두를 차가운 물로 추출하여 한정된 양만 제공됩니다. 깊은 풍미의 새로운 커피 경험을 즐겨보세요.',
        type: 'coldBrew',
    },
    {
        name: '자바 칩 프라푸치노',
        price: 7000,
        imgUrl: './image/프라푸치노/자바 칩 프라푸치노.jpg',
        description: '스타벅스 바리스타의 정성으로 탄생한 콜드 브루! 콜드 브루 전용 원두를 차가운 물로 추출하여 한정된 양만 제공됩니다. 깊은 풍미의 새로운 커피 경험을 즐겨보세요.',
        type: 'frappuccino',
    },
    {
        name: '제주 말차 크림 프라푸치노',
        price: 7000,
        imgUrl: './image/프라푸치노/제주 말차 크림 프라푸치노.jpg',
        description: '스타벅스 바리스타의 정성으로 탄생한 콜드 브루! 콜드 브루 전용 원두를 차가운 물로 추출하여 한정된 양만 제공됩니다. 깊은 풍미의 새로운 커피 경험을 즐겨보세요.',
        type: 'frappuccino',
    },
];

export default data;